# Generated by Django 4.2.2 on 2023-06-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subplan_subplanfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='highlight_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
