# Generated by Django 4.2.2 on 2023-06-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_subscription_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='mobil',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='subs',
            new_name='user',
        ),
    ]
