# Generated by Django 4.2.2 on 2023-06-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
