# Generated by Django 4.2.2 on 2023-06-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_trainermsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainermsg',
            name='user_type',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
