# Generated by Django 4.2.2 on 2023-06-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_trainermsg_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermsg',
            name='user_type',
        ),
    ]
