# Generated by Django 4.2.2 on 2023-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_trainermsg_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('logo_img', models.ImageField(upload_to='app_logos/')),
            ],
        ),
    ]
