# Generated by Django 4.2.2 on 2023-06-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='plan',
        ),
    ]
