# Generated by Django 4.2.2 on 2023-06-14 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_attendance_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Login',
            new_name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Logout',
        ),
    ]
