# Generated by Django 4.2.2 on 2023-06-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_login_attendance_hora_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='hora_entrada',
        ),
    ]
