# Generated by Django 4.2.2 on 2023-06-14 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_remove_attendance_user_attendance_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
