# Generated by Django 4.2.2 on 2023-06-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_attendance_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reg_date',
            field=models.DateField(null=True),
        ),
    ]
