# Generated by Django 4.2.2 on 2023-06-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_attendance_plan_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subscriber'),
        ),
    ]
